name: Build Fabric Mod

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21

      - name: List all files in the repo
        run: |
          echo "Listing all files in the repository:"
          ls -lR  # List all files recursively to ensure gradlew is in the right place

      - name: Make gradlew executable
        run: chmod +x gradlew  # Ensure gradlew is executable

      - name: Verify gradlew permissions
        run: ls -l gradlew  # Confirm gradlew has executable permissions

      - name: Build with Gradle
        run: ./gradlew build --stacktrace  # Attempt the build again

      - name: Upload built jar
        uses: actions/upload-artifact@v4
        with:
          name: CrosshairAddons-1.21.8
          path: build/libs/*.jar
