name: Build Fabric Mod

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21

      - name: List directory structure and check gradlew
        run: |
          echo "Listing all files in the repository:"
          ls -lR  # List files recursively to make sure gradlew is there

      - name: Make gradlew executable (again)
        run: chmod +x gradlew

      - name: Verify gradlew permissions
        run: ls -l gradlew  # Check permissions of gradlew after chmod

      - name: Build with Gradle
        run: ./gradlew build --stacktrace

      - name: Upload built jar
        uses: actions/upload-artifact@v4
        with:
          name: CrosshairAddons-1.21.8
          path: build/libs/*.jar
