name: Build Fabric Mod

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Java 17
      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      # Step 3: Use Gradle Build Action (no need to manually run gradlew)
      - name: Run Gradle Build
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build

      # Step 4: Upload the resulting .jar file
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: CrosshairAddons-1.21.8
          path: build/libs/*.jar
